import {strict as assert} from 'node:assert';
import {test} from 'node:test';
import {deck,initial,reducer,shuffle,stages} from '../app/game.ts';
function invariant(s:typeof initial){const counts=new Map<number,number>();for(const c of s.cards.filter(c=>!c.matched))counts.set(c.fruit,(counts.get(c.fruit)||0)+1);assert.ok([...counts.values()].every(n=>n%2===0));assert.equal(new Set(s.cards.map(c=>c.id)).size,stages[s.stage]);}
const play=(stage=0)=>reducer(reducer(initial,{type:'start',cards:shuffle(deck(stage)),stage}),{type:'ready'});
function finish(s:typeof initial){while(s.phase==='play'){const one=s.cards.find(c=>!c.matched)!;const two=s.cards.find(c=>!c.matched&&c.id!==one.id&&c.fruit===one.fruit)!;s=reducer(s,{type:'flip',id:one.id});s=reducer(s,{type:'flip',id:two.id});s=reducer(s,{type:'resolve'});invariant(s);}return s;}
test('100 full ten-stage runs preserve pairs and advance through the final victory',()=>{for(let run=0;run<100;run++){let s=play();for(let stage=0;stage<10;stage++){assert.equal(s.stage,stage);assert.equal(s.cards.length,stages[stage]);assert.equal(s.moves,0);s=finish(s);assert.equal(s.phase,'won');assert.equal(s.moves,stages[stage]/2);if(stage<9){s=reducer(s,{type:'next'});assert.equal(s.phase,'preview');s=reducer(s,{type:'ready'});}else{assert.equal(reducer(s,{type:'next'}),s);assert.ok(s.message.includes('10개'));}}}});
test('mismatch locks third card; retry stays on same stage; next cannot skip',()=>{let s=play(5);assert.equal(reducer(s,{type:'next'}),s);const a=s.cards[0];const b=s.cards.find(c=>c.fruit!==a.fruit)!;s=reducer(s,{type:'flip',id:a.id});assert.equal(reducer(s,{type:'flip',id:a.id}),s);s=reducer(s,{type:'flip',id:b.id});assert.equal(reducer(s,{type:'flip',id:999}),s);s=reducer(s,{type:'resolve'});assert.equal(s.selected.length,0);assert.equal(s.moves,1);assert.equal(s.cards.filter(c=>c.matched).length,0);s=reducer(s,{type:'start',cards:deck(s.stage)});assert.equal(s.stage,5);assert.equal(s.moves,0);assert.equal(s.phase,'preview');});
test('final stage resets back to the first stage',()=>{let s=finish(play(9));s=reducer(s,{type:'start',cards:deck(0),stage:0});assert.equal(s.stage,0);assert.equal(s.cards.length,8);assert.equal(s.moves,0);});

test("every stage fills four columns with complete image pairs",()=>{for(let stage=0;stage<10;stage++){assert.equal(stages[stage]%4,0);assert.equal(deck(stage).length,stages[stage]);invariant(play(stage));}});
test('hint preserves cards and selected card, locks flips and expires back into play',()=>{let s=play(3);s=reducer(s,{type:'flip',id:s.cards[0].id});const before=s;s=reducer(s,{type:'hint'});assert.equal(s.phase,'hint');assert.equal(s.cards,before.cards);assert.deepEqual(s.selected,before.selected);assert.equal(s.moves,before.moves);assert.equal(reducer(s,{type:'flip',id:s.cards[1].id}),s);assert.equal(reducer(s,{type:'hint'}),s);s=reducer(s,{type:'ready'});assert.equal(s.phase,'play');assert.deepEqual(s.selected,before.selected);assert.equal(reducer(initial,{type:'hint'}),initial);});
test('hint cannot interrupt a pending match and can be used again after expiry',()=>{let s=play();s=reducer(s,{type:'flip',id:s.cards[0].id});s=reducer(s,{type:'flip',id:s.cards[1].id});assert.equal(reducer(s,{type:'hint'}),s);s=reducer(s,{type:'resolve'});s=reducer(s,{type:'hint'});assert.equal(s.phase,'hint');s=reducer(s,{type:'ready'});s=reducer(s,{type:'hint'});assert.equal(s.phase,'hint');});
